name: deploy prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-prod
          path: ./

  deploy:
    runs-on: [prod2]
    needs: build
    steps:
      - name: Ensure /home/sites/web exists
        run: mkdir -p /home/sites/web

      - name: Clean
        run: rm -rf /home/sites/web/*

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-prod
          path: /home/sites/web/
