name: Deploy to GitHub Pages (v2)

on:
  push:
    branches:
      - v2

jobs:
  deploy:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages        # Rama donde se desplegará el contenido
          folder: .               # Carpeta raíz (contiene los archivos HTML, CSS y JS)
          clean: true             # Limpia el contenido previo en gh-pages
